-- ============================================================
-- Simple Social Media Platform - DML (Sample Data)
-- ============================================================

USE simple_social_media;

-- ============================================================
-- Sample Users
-- password = "Test1234!" hashed (SHA-256 with salt)
-- For demo purposes only; real hash generated by application
-- ============================================================
INSERT INTO users (phone, user_name, email, password, salt, biography) VALUES
('0911000001', 'Alice Wang',   'alice@example.com',  'PLACEHOLDER_HASH_1', 'PLACEHOLDER_SALT_1', '大家好，我是 Alice！'),
('0911000002', 'Bob Chen',     'bob@example.com',    'PLACEHOLDER_HASH_2', 'PLACEHOLDER_SALT_2', 'Hello, I am Bob.'),
('0911000003', 'Carol Liu',    'carol@example.com',  'PLACEHOLDER_HASH_3', 'PLACEHOLDER_SALT_3', '喜歡攝影和旅遊 📷');

-- ============================================================
-- Sample Posts
-- ============================================================
INSERT INTO posts (user_id, content) VALUES
(1, '今天天氣很好，出去走走！'),
(2, 'Spring Boot 真的很方便！'),
(1, 'Vue 3 + Composition API 讚讚讚');

-- ============================================================
-- Sample Comments
-- ============================================================
INSERT INTO comments (user_id, post_id, content) VALUES
(2, 1, '真的耶，今天很適合出門！'),
(3, 1, '+1，我也去公園了'),
(1, 2, '我也這樣覺得！'),
(3, 3, 'Vue 3 Pinia 也很棒喔');
